_wandb:
    value:
        cli_version: 0.21.0
        e:
            94lb86x8y5nc871a5vzs2a9ojs5i9br3:
                codePath: model.ipynb
                codePathLocal: model.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "338353451008"
                        used: "53705846784"
                email: atharvdwivedi8@gmail.com
                executable: c:\Python\python.exe
                host: LAPTOP-I3CGMBQJ
                memory:
                    total: "13771653120"
                os: Windows-11-10.0.26100-SP0
                program: d:\Atharva\Implementations\VQGAN\model.ipynb
                python: CPython 3.12.3
                root: d:\Atharva\Implementations\VQGAN
                startedAt: "2025-08-03T01:10:50.855098Z"
                writerId: 94lb86x8y5nc871a5vzs2a9ojs5i9br3
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 2
                - 16
            "4": 3.12.3
            "5": 0.21.0
            "8":
                - 1
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 32
beta:
    value: 0.25
device:
    value: cpu
embedding_dim:
    value: 256
epochs:
    value: 20
hidden_channels:
    value: 128
img_size:
    value: 64
in_channels:
    value: 3
latent_dim:
    value: 256
log_interval:
    value: 100
lr:
    value: 0.0002
num_embeddings:
    value: 1024
out_channels:
    value: 3
project_name:
    value: VQ_VAE
save_dir:
    value: ./saves
save_interval:
    value: 1
use_wandb:
    value: true
